# Generated by Django 3.2.9 on 2021-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopView', '0002_auto_20211209_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_features',
            name='Avtor_name',
        ),
        migrations.RemoveField(
            model_name='product_features',
            name='article',
        ),
        migrations.RemoveField(
            model_name='product_features',
            name='comment_text',
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ник')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('Likes', models.ManyToManyField(to='ShopView.product')),
            ],
        ),
    ]
