# Generated by Django 4.0.1 on 2022-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=200, verbose_name='Имя животного')),
                ('animal_description', models.TextField(max_length=2000, verbose_name='Описание животного')),
                ('animal_features', models.TextField(max_length=2000, verbose_name='Особенности животного')),
                ('animal_habitat', models.TextField(max_length=1500, verbose_name='Места обитания животного')),
                ('animal_intresting', models.TextField(max_length=1500, verbose_name='Интересные факты о животном')),
                ('animal_photo', models.ImageField(upload_to='image/%d-%m-%Y/', verbose_name='Фото животного')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
